[2013-03-21 16:10:56] log.ERROR: exception 'Symfony\Component\HttpKernel\Exception\FatalErrorException' with message 'Error: Class 'App\Controllers\Api\Frontend\Client\Orders\StoreRelatedApiController' not found in /Users/johannes/Dropbox/Code/htdocs/sub2home/dev/server/app/controllers/api/frontend/client/orders/TestOrderController.php line 9' in /Users/johannes/Dropbox/Code/htdocs/sub2home/dev/server/app/controllers/api/frontend/client/orders/TestOrderController.php:9
Stack trace:
#0 /Users/johannes/Dropbox/Code/htdocs/sub2home/dev/server/bootstrap/compiled.php(4019): Symfony\Component\HttpKernel\Debug\ErrorHandler->handleFatal()
#1 [internal function]: Illuminate\Exception\ExceptionServiceProvider->Illuminate\Exception\{closure}()
#2 {main} [] []
[2013-03-21 16:54:28] log.ERROR: exception 'Symfony\Component\HttpKernel\Exception\FatalErrorException' with message 'Error: Call to undefined method App\Controllers\Services\Image\DecodeQRCodeService::decode() in /Users/johannes/Dropbox/Code/htdocs/sub2home/dev/server/app/controllers/api/services/DecodeQRCodeController.php line 17' in /Users/johannes/Dropbox/Code/htdocs/sub2home/dev/server/app/controllers/api/services/DecodeQRCodeController.php:17
Stack trace:
#0 /Users/johannes/Dropbox/Code/htdocs/sub2home/dev/server/bootstrap/compiled.php(4019): Symfony\Component\HttpKernel\Debug\ErrorHandler->handleFatal()
#1 [internal function]: Illuminate\Exception\ExceptionServiceProvider->Illuminate\Exception\{closure}()
#2 {main} [] []
[2013-03-21 16:54:56] log.INFO:  [] []
[2013-03-21 16:57:29] log.INFO:  [] []
[2013-03-21 16:57:56] log.INFO:  [] []
[2013-03-21 17:05:15] log.ERROR: exception 'ErrorException' with message 'Notice: Undefined variable: outputArray in /Users/johannes/Dropbox/Code/htdocs/sub2home/dev/server/app/controllers/services/image/DecodeQRCodeService.php line 24' in /Users/johannes/Dropbox/Code/htdocs/sub2home/dev/server/app/controllers/services/image/DecodeQRCodeService.php:24
Stack trace:
#0 /Users/johannes/Dropbox/Code/htdocs/sub2home/dev/server/app/controllers/services/image/DecodeQRCodeService.php(24): Symfony\Component\HttpKernel\Debug\ErrorHandler->handle(8, 'Undefined varia...', '/Users/johannes...', 24, Array)
#1 /Users/johannes/Dropbox/Code/htdocs/sub2home/dev/server/app/controllers/services/image/DecodeQRCodeService.php(14): App\Controllers\Services\Image\DecodeQRCodeService::decodeImageWithZxing('/Users/johannes...')
#2 /Users/johannes/Dropbox/Code/htdocs/sub2home/dev/server/app/controllers/api/services/DecodeQRCodeController.php(17): App\Controllers\Services\Image\DecodeQRCodeService::decodeImage('/Users/johannes...')
#3 [internal function]: App\Controllers\Api\Services\DecodeQRCodeController->decode()
#4 /Users/johannes/Dropbox/Code/htdocs/sub2home/dev/server/vendor/laravel/framework/src/Illuminate/Routing/Controllers/Controller.php(138): call_user_func_array(Array, Array)
#5 /Users/johannes/Dropbox/Code/htdocs/sub2home/dev/server/vendor/laravel/framework/src/Illuminate/Routing/Controllers/Controller.php(115): Illuminate\Routing\Controllers\Controller->callMethod('decode', Array)
#6 /Users/johannes/Dropbox/Code/htdocs/sub2home/dev/server/bootstrap/compiled.php(6977): Illuminate\Routing\Controllers\Controller->callAction(Object(Illuminate\Foundation\Application), Object(Illuminate\Routing\Router), 'decode', Array)
#7 [internal function]: Illuminate\Routing\Router->Illuminate\Routing\{closure}()
#8 /Users/johannes/Dropbox/Code/htdocs/sub2home/dev/server/bootstrap/compiled.php(12961): call_user_func_array(Object(Closure), Array)
#9 /Users/johannes/Dropbox/Code/htdocs/sub2home/dev/server/bootstrap/compiled.php(12942): Illuminate\Routing\Route->callCallable()
#10 /Users/johannes/Dropbox/Code/htdocs/sub2home/dev/server/bootstrap/compiled.php(6997): Illuminate\Routing\Route->run(Object(Illuminate\Http\Request))
#11 /Users/johannes/Dropbox/Code/htdocs/sub2home/dev/server/bootstrap/compiled.php(946): Illuminate\Routing\Router->dispatch(Object(Illuminate\Http\Request))
#12 /Users/johannes/Dropbox/Code/htdocs/sub2home/dev/server/bootstrap/compiled.php(934): Illuminate\Foundation\Application->dispatch(Object(Illuminate\Http\Request))
#13 /Users/johannes/Dropbox/Code/htdocs/sub2home/dev/server/public/index.php(51): Illuminate\Foundation\Application->run()
#14 {main} [] []
[2013-03-21 17:46:45] log.ERROR: exception 'Symfony\Component\HttpKernel\Exception\NotFoundHttpException' in /Users/johannes/Dropbox/Code/htdocs/sub2home/dev/server/bootstrap/compiled.php:7317
Stack trace:
#0 /Users/johannes/Dropbox/Code/htdocs/sub2home/dev/server/bootstrap/compiled.php(7020): Illuminate\Routing\Router->handleRoutingException(Object(Symfony\Component\Routing\Exception\ResourceNotFoundException))
#1 /Users/johannes/Dropbox/Code/htdocs/sub2home/dev/server/bootstrap/compiled.php(6996): Illuminate\Routing\Router->findRoute(Object(Illuminate\Http\Request))
#2 /Users/johannes/Dropbox/Code/htdocs/sub2home/dev/server/bootstrap/compiled.php(946): Illuminate\Routing\Router->dispatch(Object(Illuminate\Http\Request))
#3 /Users/johannes/Dropbox/Code/htdocs/sub2home/dev/server/bootstrap/compiled.php(934): Illuminate\Foundation\Application->dispatch(Object(Illuminate\Http\Request))
#4 /Users/johannes/Dropbox/Code/htdocs/sub2home/dev/server/public/index.php(51): Illuminate\Foundation\Application->run()
#5 {main} [] []
[2013-03-21 17:47:19] log.ERROR: exception 'Symfony\Component\HttpKernel\Exception\NotFoundHttpException' in /Users/johannes/Dropbox/Code/htdocs/sub2home/dev/server/bootstrap/compiled.php:7317
Stack trace:
#0 /Users/johannes/Dropbox/Code/htdocs/sub2home/dev/server/bootstrap/compiled.php(7020): Illuminate\Routing\Router->handleRoutingException(Object(Symfony\Component\Routing\Exception\ResourceNotFoundException))
#1 /Users/johannes/Dropbox/Code/htdocs/sub2home/dev/server/bootstrap/compiled.php(6996): Illuminate\Routing\Router->findRoute(Object(Illuminate\Http\Request))
#2 /Users/johannes/Dropbox/Code/htdocs/sub2home/dev/server/bootstrap/compiled.php(946): Illuminate\Routing\Router->dispatch(Object(Illuminate\Http\Request))
#3 /Users/johannes/Dropbox/Code/htdocs/sub2home/dev/server/bootstrap/compiled.php(934): Illuminate\Foundation\Application->dispatch(Object(Illuminate\Http\Request))
#4 /Users/johannes/Dropbox/Code/htdocs/sub2home/dev/server/public/index.php(51): Illuminate\Foundation\Application->run()
#5 {main} [] []
[2013-03-21 17:47:24] log.ERROR: exception 'Symfony\Component\HttpKernel\Exception\NotFoundHttpException' in /Users/johannes/Dropbox/Code/htdocs/sub2home/dev/server/bootstrap/compiled.php:7317
Stack trace:
#0 /Users/johannes/Dropbox/Code/htdocs/sub2home/dev/server/bootstrap/compiled.php(7020): Illuminate\Routing\Router->handleRoutingException(Object(Symfony\Component\Routing\Exception\ResourceNotFoundException))
#1 /Users/johannes/Dropbox/Code/htdocs/sub2home/dev/server/bootstrap/compiled.php(6996): Illuminate\Routing\Router->findRoute(Object(Illuminate\Http\Request))
#2 /Users/johannes/Dropbox/Code/htdocs/sub2home/dev/server/bootstrap/compiled.php(946): Illuminate\Routing\Router->dispatch(Object(Illuminate\Http\Request))
#3 /Users/johannes/Dropbox/Code/htdocs/sub2home/dev/server/bootstrap/compiled.php(934): Illuminate\Foundation\Application->dispatch(Object(Illuminate\Http\Request))
#4 /Users/johannes/Dropbox/Code/htdocs/sub2home/dev/server/public/index.php(51): Illuminate\Foundation\Application->run()
#5 {main} [] []
[2013-03-21 17:48:18] log.ERROR: exception 'Symfony\Component\HttpKernel\Exception\NotFoundHttpException' in /Users/johannes/Dropbox/Code/htdocs/sub2home/dev/server/bootstrap/compiled.php:7317
Stack trace:
#0 /Users/johannes/Dropbox/Code/htdocs/sub2home/dev/server/bootstrap/compiled.php(7020): Illuminate\Routing\Router->handleRoutingException(Object(Symfony\Component\Routing\Exception\ResourceNotFoundException))
#1 /Users/johannes/Dropbox/Code/htdocs/sub2home/dev/server/bootstrap/compiled.php(6996): Illuminate\Routing\Router->findRoute(Object(Illuminate\Http\Request))
#2 /Users/johannes/Dropbox/Code/htdocs/sub2home/dev/server/bootstrap/compiled.php(946): Illuminate\Routing\Router->dispatch(Object(Illuminate\Http\Request))
#3 /Users/johannes/Dropbox/Code/htdocs/sub2home/dev/server/bootstrap/compiled.php(934): Illuminate\Foundation\Application->dispatch(Object(Illuminate\Http\Request))
#4 /Users/johannes/Dropbox/Code/htdocs/sub2home/dev/server/public/index.php(51): Illuminate\Foundation\Application->run()
#5 {main} [] []
[2013-03-21 17:48:20] log.ERROR: exception 'Symfony\Component\HttpKernel\Exception\NotFoundHttpException' in /Users/johannes/Dropbox/Code/htdocs/sub2home/dev/server/bootstrap/compiled.php:7317
Stack trace:
#0 /Users/johannes/Dropbox/Code/htdocs/sub2home/dev/server/bootstrap/compiled.php(7020): Illuminate\Routing\Router->handleRoutingException(Object(Symfony\Component\Routing\Exception\ResourceNotFoundException))
#1 /Users/johannes/Dropbox/Code/htdocs/sub2home/dev/server/bootstrap/compiled.php(6996): Illuminate\Routing\Router->findRoute(Object(Illuminate\Http\Request))
#2 /Users/johannes/Dropbox/Code/htdocs/sub2home/dev/server/bootstrap/compiled.php(946): Illuminate\Routing\Router->dispatch(Object(Illuminate\Http\Request))
#3 /Users/johannes/Dropbox/Code/htdocs/sub2home/dev/server/bootstrap/compiled.php(934): Illuminate\Foundation\Application->dispatch(Object(Illuminate\Http\Request))
#4 /Users/johannes/Dropbox/Code/htdocs/sub2home/dev/server/public/index.php(51): Illuminate\Foundation\Application->run()
#5 {main} [] []
[2013-03-21 17:48:33] log.ERROR: exception 'Symfony\Component\HttpKernel\Exception\NotFoundHttpException' in /Users/johannes/Dropbox/Code/htdocs/sub2home/dev/server/bootstrap/compiled.php:7317
Stack trace:
#0 /Users/johannes/Dropbox/Code/htdocs/sub2home/dev/server/bootstrap/compiled.php(7020): Illuminate\Routing\Router->handleRoutingException(Object(Symfony\Component\Routing\Exception\ResourceNotFoundException))
#1 /Users/johannes/Dropbox/Code/htdocs/sub2home/dev/server/bootstrap/compiled.php(6996): Illuminate\Routing\Router->findRoute(Object(Illuminate\Http\Request))
#2 /Users/johannes/Dropbox/Code/htdocs/sub2home/dev/server/bootstrap/compiled.php(946): Illuminate\Routing\Router->dispatch(Object(Illuminate\Http\Request))
#3 /Users/johannes/Dropbox/Code/htdocs/sub2home/dev/server/bootstrap/compiled.php(934): Illuminate\Foundation\Application->dispatch(Object(Illuminate\Http\Request))
#4 /Users/johannes/Dropbox/Code/htdocs/sub2home/dev/server/public/index.php(51): Illuminate\Foundation\Application->run()
#5 {main} [] []
[2013-03-21 17:48:34] log.ERROR: exception 'Symfony\Component\HttpKernel\Exception\NotFoundHttpException' in /Users/johannes/Dropbox/Code/htdocs/sub2home/dev/server/bootstrap/compiled.php:7317
Stack trace:
#0 /Users/johannes/Dropbox/Code/htdocs/sub2home/dev/server/bootstrap/compiled.php(7020): Illuminate\Routing\Router->handleRoutingException(Object(Symfony\Component\Routing\Exception\ResourceNotFoundException))
#1 /Users/johannes/Dropbox/Code/htdocs/sub2home/dev/server/bootstrap/compiled.php(6996): Illuminate\Routing\Router->findRoute(Object(Illuminate\Http\Request))
#2 /Users/johannes/Dropbox/Code/htdocs/sub2home/dev/server/bootstrap/compiled.php(946): Illuminate\Routing\Router->dispatch(Object(Illuminate\Http\Request))
#3 /Users/johannes/Dropbox/Code/htdocs/sub2home/dev/server/bootstrap/compiled.php(934): Illuminate\Foundation\Application->dispatch(Object(Illuminate\Http\Request))
#4 /Users/johannes/Dropbox/Code/htdocs/sub2home/dev/server/public/index.php(51): Illuminate\Foundation\Application->run()
#5 {main} [] []
[2013-03-21 17:48:59] log.ERROR: exception 'Symfony\Component\HttpKernel\Exception\NotFoundHttpException' in /Users/johannes/Dropbox/Code/htdocs/sub2home/dev/server/bootstrap/compiled.php:7317
Stack trace:
#0 /Users/johannes/Dropbox/Code/htdocs/sub2home/dev/server/bootstrap/compiled.php(7020): Illuminate\Routing\Router->handleRoutingException(Object(Symfony\Component\Routing\Exception\ResourceNotFoundException))
#1 /Users/johannes/Dropbox/Code/htdocs/sub2home/dev/server/bootstrap/compiled.php(6996): Illuminate\Routing\Router->findRoute(Object(Illuminate\Http\Request))
#2 /Users/johannes/Dropbox/Code/htdocs/sub2home/dev/server/bootstrap/compiled.php(946): Illuminate\Routing\Router->dispatch(Object(Illuminate\Http\Request))
#3 /Users/johannes/Dropbox/Code/htdocs/sub2home/dev/server/bootstrap/compiled.php(934): Illuminate\Foundation\Application->dispatch(Object(Illuminate\Http\Request))
#4 /Users/johannes/Dropbox/Code/htdocs/sub2home/dev/server/public/index.php(51): Illuminate\Foundation\Application->run()
#5 {main} [] []
[2013-03-21 17:49:01] log.ERROR: exception 'Symfony\Component\HttpKernel\Exception\NotFoundHttpException' in /Users/johannes/Dropbox/Code/htdocs/sub2home/dev/server/bootstrap/compiled.php:7317
Stack trace:
#0 /Users/johannes/Dropbox/Code/htdocs/sub2home/dev/server/bootstrap/compiled.php(7020): Illuminate\Routing\Router->handleRoutingException(Object(Symfony\Component\Routing\Exception\ResourceNotFoundException))
#1 /Users/johannes/Dropbox/Code/htdocs/sub2home/dev/server/bootstrap/compiled.php(6996): Illuminate\Routing\Router->findRoute(Object(Illuminate\Http\Request))
#2 /Users/johannes/Dropbox/Code/htdocs/sub2home/dev/server/bootstrap/compiled.php(946): Illuminate\Routing\Router->dispatch(Object(Illuminate\Http\Request))
#3 /Users/johannes/Dropbox/Code/htdocs/sub2home/dev/server/bootstrap/compiled.php(934): Illuminate\Foundation\Application->dispatch(Object(Illuminate\Http\Request))
#4 /Users/johannes/Dropbox/Code/htdocs/sub2home/dev/server/public/index.php(51): Illuminate\Foundation\Application->run()
#5 {main} [] []
[2013-03-21 17:49:02] log.ERROR: exception 'Symfony\Component\HttpKernel\Exception\NotFoundHttpException' in /Users/johannes/Dropbox/Code/htdocs/sub2home/dev/server/bootstrap/compiled.php:7317
Stack trace:
#0 /Users/johannes/Dropbox/Code/htdocs/sub2home/dev/server/bootstrap/compiled.php(7020): Illuminate\Routing\Router->handleRoutingException(Object(Symfony\Component\Routing\Exception\ResourceNotFoundException))
#1 /Users/johannes/Dropbox/Code/htdocs/sub2home/dev/server/bootstrap/compiled.php(6996): Illuminate\Routing\Router->findRoute(Object(Illuminate\Http\Request))
#2 /Users/johannes/Dropbox/Code/htdocs/sub2home/dev/server/bootstrap/compiled.php(946): Illuminate\Routing\Router->dispatch(Object(Illuminate\Http\Request))
#3 /Users/johannes/Dropbox/Code/htdocs/sub2home/dev/server/bootstrap/compiled.php(934): Illuminate\Foundation\Application->dispatch(Object(Illuminate\Http\Request))
#4 /Users/johannes/Dropbox/Code/htdocs/sub2home/dev/server/public/index.php(51): Illuminate\Foundation\Application->run()
#5 {main} [] []
[2013-03-21 17:49:08] log.ERROR: exception 'Symfony\Component\HttpKernel\Exception\NotFoundHttpException' in /Users/johannes/Dropbox/Code/htdocs/sub2home/dev/server/bootstrap/compiled.php:7317
Stack trace:
#0 /Users/johannes/Dropbox/Code/htdocs/sub2home/dev/server/bootstrap/compiled.php(7020): Illuminate\Routing\Router->handleRoutingException(Object(Symfony\Component\Routing\Exception\ResourceNotFoundException))
#1 /Users/johannes/Dropbox/Code/htdocs/sub2home/dev/server/bootstrap/compiled.php(6996): Illuminate\Routing\Router->findRoute(Object(Illuminate\Http\Request))
#2 /Users/johannes/Dropbox/Code/htdocs/sub2home/dev/server/bootstrap/compiled.php(946): Illuminate\Routing\Router->dispatch(Object(Illuminate\Http\Request))
#3 /Users/johannes/Dropbox/Code/htdocs/sub2home/dev/server/bootstrap/compiled.php(934): Illuminate\Foundation\Application->dispatch(Object(Illuminate\Http\Request))
#4 /Users/johannes/Dropbox/Code/htdocs/sub2home/dev/server/public/index.php(51): Illuminate\Foundation\Application->run()
#5 {main} [] []
[2013-03-21 18:11:20] log.ERROR: exception 'Symfony\Component\HttpKernel\Exception\FatalErrorException' with message 'Error: Class 'App\Controllers\Api\Services\Validator' not found in /Users/johannes/Dropbox/Code/htdocs/sub2home/dev/server/app/controllers/api/services/DecodeQRCodeController.php line 23' in /Users/johannes/Dropbox/Code/htdocs/sub2home/dev/server/app/controllers/api/services/DecodeQRCodeController.php:23
Stack trace:
#0 /Users/johannes/Dropbox/Code/htdocs/sub2home/dev/server/bootstrap/compiled.php(4019): Symfony\Component\HttpKernel\Debug\ErrorHandler->handleFatal()
#1 [internal function]: Illuminate\Exception\ExceptionServiceProvider->Illuminate\Exception\{closure}()
#2 {main} [] []
[2013-03-21 18:11:32] log.ERROR: exception 'ErrorException' with message 'Catchable Fatal Error: Argument 1 passed to Illuminate\Validation\Factory::make() must be of the type array, boolean given, called in /Users/johannes/Dropbox/Code/htdocs/sub2home/dev/server/bootstrap/compiled.php on line 4262 and defined in /Users/johannes/Dropbox/Code/htdocs/sub2home/dev/server/vendor/laravel/framework/src/Illuminate/Validation/Factory.php line 62' in /Users/johannes/Dropbox/Code/htdocs/sub2home/dev/server/vendor/laravel/framework/src/Illuminate/Validation/Factory.php:62
Stack trace:
#0 /Users/johannes/Dropbox/Code/htdocs/sub2home/dev/server/vendor/laravel/framework/src/Illuminate/Validation/Factory.php(62): Symfony\Component\HttpKernel\Debug\ErrorHandler->handle(4096, 'Argument 1 pass...', '/Users/johannes...', 62, Array)
#1 /Users/johannes/Dropbox/Code/htdocs/sub2home/dev/server/bootstrap/compiled.php(4262): Illuminate\Validation\Factory->make(false, Array)
#2 /Users/johannes/Dropbox/Code/htdocs/sub2home/dev/server/app/controllers/api/services/DecodeQRCodeController.php(24): Illuminate\Support\Facades\Facade::__callStatic('make', Array)
#3 /Users/johannes/Dropbox/Code/htdocs/sub2home/dev/server/app/controllers/api/services/DecodeQRCodeController.php(24): Illuminate\Support\Facades\Validator::make(false, Array)
#4 [internal function]: App\Controllers\Api\Services\DecodeQRCodeController->decode()
#5 /Users/johannes/Dropbox/Code/htdocs/sub2home/dev/server/vendor/laravel/framework/src/Illuminate/Routing/Controllers/Controller.php(138): call_user_func_array(Array, Array)
#6 /Users/johannes/Dropbox/Code/htdocs/sub2home/dev/server/vendor/laravel/framework/src/Illuminate/Routing/Controllers/Controller.php(115): Illuminate\Routing\Controllers\Controller->callMethod('decode', Array)
#7 /Users/johannes/Dropbox/Code/htdocs/sub2home/dev/server/bootstrap/compiled.php(6977): Illuminate\Routing\Controllers\Controller->callAction(Object(Illuminate\Foundation\Application), Object(Illuminate\Routing\Router), 'decode', Array)
#8 [internal function]: Illuminate\Routing\Router->Illuminate\Routing\{closure}()
#9 /Users/johannes/Dropbox/Code/htdocs/sub2home/dev/server/bootstrap/compiled.php(12961): call_user_func_array(Object(Closure), Array)
#10 /Users/johannes/Dropbox/Code/htdocs/sub2home/dev/server/bootstrap/compiled.php(12942): Illuminate\Routing\Route->callCallable()
#11 /Users/johannes/Dropbox/Code/htdocs/sub2home/dev/server/bootstrap/compiled.php(6997): Illuminate\Routing\Route->run(Object(Illuminate\Http\Request))
#12 /Users/johannes/Dropbox/Code/htdocs/sub2home/dev/server/bootstrap/compiled.php(946): Illuminate\Routing\Router->dispatch(Object(Illuminate\Http\Request))
#13 /Users/johannes/Dropbox/Code/htdocs/sub2home/dev/server/bootstrap/compiled.php(934): Illuminate\Foundation\Application->dispatch(Object(Illuminate\Http\Request))
#14 /Users/johannes/Dropbox/Code/htdocs/sub2home/dev/server/public/index.php(51): Illuminate\Foundation\Application->run()
#15 {main} [] []
[2013-03-21 18:12:26] log.ERROR: exception 'ErrorException' with message 'Notice: Undefined variable: input in /Users/johannes/Dropbox/Code/htdocs/sub2home/dev/server/app/controllers/api/services/DecodeQRCodeController.php line 32' in /Users/johannes/Dropbox/Code/htdocs/sub2home/dev/server/app/controllers/api/services/DecodeQRCodeController.php:32
Stack trace:
#0 /Users/johannes/Dropbox/Code/htdocs/sub2home/dev/server/app/controllers/api/services/DecodeQRCodeController.php(32): Symfony\Component\HttpKernel\Debug\ErrorHandler->handle(8, 'Undefined varia...', '/Users/johannes...', 32, Array)
#1 [internal function]: App\Controllers\Api\Services\DecodeQRCodeController->decode()
#2 /Users/johannes/Dropbox/Code/htdocs/sub2home/dev/server/vendor/laravel/framework/src/Illuminate/Routing/Controllers/Controller.php(138): call_user_func_array(Array, Array)
#3 /Users/johannes/Dropbox/Code/htdocs/sub2home/dev/server/vendor/laravel/framework/src/Illuminate/Routing/Controllers/Controller.php(115): Illuminate\Routing\Controllers\Controller->callMethod('decode', Array)
#4 /Users/johannes/Dropbox/Code/htdocs/sub2home/dev/server/bootstrap/compiled.php(6977): Illuminate\Routing\Controllers\Controller->callAction(Object(Illuminate\Foundation\Application), Object(Illuminate\Routing\Router), 'decode', Array)
#5 [internal function]: Illuminate\Routing\Router->Illuminate\Routing\{closure}()
#6 /Users/johannes/Dropbox/Code/htdocs/sub2home/dev/server/bootstrap/compiled.php(12961): call_user_func_array(Object(Closure), Array)
#7 /Users/johannes/Dropbox/Code/htdocs/sub2home/dev/server/bootstrap/compiled.php(12942): Illuminate\Routing\Route->callCallable()
#8 /Users/johannes/Dropbox/Code/htdocs/sub2home/dev/server/bootstrap/compiled.php(6997): Illuminate\Routing\Route->run(Object(Illuminate\Http\Request))
#9 /Users/johannes/Dropbox/Code/htdocs/sub2home/dev/server/bootstrap/compiled.php(946): Illuminate\Routing\Router->dispatch(Object(Illuminate\Http\Request))
#10 /Users/johannes/Dropbox/Code/htdocs/sub2home/dev/server/bootstrap/compiled.php(934): Illuminate\Foundation\Application->dispatch(Object(Illuminate\Http\Request))
#11 /Users/johannes/Dropbox/Code/htdocs/sub2home/dev/server/public/index.php(51): Illuminate\Foundation\Application->run()
#12 {main} [] []
[2013-03-21 18:12:34] log.ERROR: exception 'ErrorException' with message 'Notice: Undefined variable: img in /Users/johannes/Dropbox/Code/htdocs/sub2home/dev/server/app/controllers/api/services/DecodeQRCodeController.php line 39' in /Users/johannes/Dropbox/Code/htdocs/sub2home/dev/server/app/controllers/api/services/DecodeQRCodeController.php:39
Stack trace:
#0 /Users/johannes/Dropbox/Code/htdocs/sub2home/dev/server/app/controllers/api/services/DecodeQRCodeController.php(39): Symfony\Component\HttpKernel\Debug\ErrorHandler->handle(8, 'Undefined varia...', '/Users/johannes...', 39, Array)
#1 [internal function]: App\Controllers\Api\Services\DecodeQRCodeController->decode()
#2 /Users/johannes/Dropbox/Code/htdocs/sub2home/dev/server/vendor/laravel/framework/src/Illuminate/Routing/Controllers/Controller.php(138): call_user_func_array(Array, Array)
#3 /Users/johannes/Dropbox/Code/htdocs/sub2home/dev/server/vendor/laravel/framework/src/Illuminate/Routing/Controllers/Controller.php(115): Illuminate\Routing\Controllers\Controller->callMethod('decode', Array)
#4 /Users/johannes/Dropbox/Code/htdocs/sub2home/dev/server/bootstrap/compiled.php(6977): Illuminate\Routing\Controllers\Controller->callAction(Object(Illuminate\Foundation\Application), Object(Illuminate\Routing\Router), 'decode', Array)
#5 [internal function]: Illuminate\Routing\Router->Illuminate\Routing\{closure}()
#6 /Users/johannes/Dropbox/Code/htdocs/sub2home/dev/server/bootstrap/compiled.php(12961): call_user_func_array(Object(Closure), Array)
#7 /Users/johannes/Dropbox/Code/htdocs/sub2home/dev/server/bootstrap/compiled.php(12942): Illuminate\Routing\Route->callCallable()
#8 /Users/johannes/Dropbox/Code/htdocs/sub2home/dev/server/bootstrap/compiled.php(6997): Illuminate\Routing\Route->run(Object(Illuminate\Http\Request))
#9 /Users/johannes/Dropbox/Code/htdocs/sub2home/dev/server/bootstrap/compiled.php(946): Illuminate\Routing\Router->dispatch(Object(Illuminate\Http\Request))
#10 /Users/johannes/Dropbox/Code/htdocs/sub2home/dev/server/bootstrap/compiled.php(934): Illuminate\Foundation\Application->dispatch(Object(Illuminate\Http\Request))
#11 /Users/johannes/Dropbox/Code/htdocs/sub2home/dev/server/public/index.php(51): Illuminate\Foundation\Application->run()
#12 {main} [] []
[2013-03-21 18:12:43] log.ERROR: exception 'ErrorException' with message 'Warning: file_put_contents(/Users/johannes/Dropbox/Code/htdocs/sub2home/dev/server/app/controllers/api/services/../storage/cache/514b3f8be8359.jpg): failed to open stream: No such file or directory in /Users/johannes/Dropbox/Code/htdocs/sub2home/dev/server/app/controllers/api/services/DecodeQRCodeController.php line 42' in /Users/johannes/Dropbox/Code/htdocs/sub2home/dev/server/app/controllers/api/services/DecodeQRCodeController.php:42
Stack trace:
#0 [internal function]: Symfony\Component\HttpKernel\Debug\ErrorHandler->handle(2, 'file_put_conten...', '/Users/johannes...', 42, Array)
#1 /Users/johannes/Dropbox/Code/htdocs/sub2home/dev/server/app/controllers/api/services/DecodeQRCodeController.php(42): file_put_contents('/Users/johannes...', '')
#2 [internal function]: App\Controllers\Api\Services\DecodeQRCodeController->decode()
#3 /Users/johannes/Dropbox/Code/htdocs/sub2home/dev/server/vendor/laravel/framework/src/Illuminate/Routing/Controllers/Controller.php(138): call_user_func_array(Array, Array)
#4 /Users/johannes/Dropbox/Code/htdocs/sub2home/dev/server/vendor/laravel/framework/src/Illuminate/Routing/Controllers/Controller.php(115): Illuminate\Routing\Controllers\Controller->callMethod('decode', Array)
#5 /Users/johannes/Dropbox/Code/htdocs/sub2home/dev/server/bootstrap/compiled.php(6977): Illuminate\Routing\Controllers\Controller->callAction(Object(Illuminate\Foundation\Application), Object(Illuminate\Routing\Router), 'decode', Array)
#6 [internal function]: Illuminate\Routing\Router->Illuminate\Routing\{closure}()
#7 /Users/johannes/Dropbox/Code/htdocs/sub2home/dev/server/bootstrap/compiled.php(12961): call_user_func_array(Object(Closure), Array)
#8 /Users/johannes/Dropbox/Code/htdocs/sub2home/dev/server/bootstrap/compiled.php(12942): Illuminate\Routing\Route->callCallable()
#9 /Users/johannes/Dropbox/Code/htdocs/sub2home/dev/server/bootstrap/compiled.php(6997): Illuminate\Routing\Route->run(Object(Illuminate\Http\Request))
#10 /Users/johannes/Dropbox/Code/htdocs/sub2home/dev/server/bootstrap/compiled.php(946): Illuminate\Routing\Router->dispatch(Object(Illuminate\Http\Request))
#11 /Users/johannes/Dropbox/Code/htdocs/sub2home/dev/server/bootstrap/compiled.php(934): Illuminate\Foundation\Application->dispatch(Object(Illuminate\Http\Request))
#12 /Users/johannes/Dropbox/Code/htdocs/sub2home/dev/server/public/index.php(51): Illuminate\Foundation\Application->run()
#13 {main} [] []
[2013-03-21 18:14:09] log.ERROR: exception 'ErrorException' with message 'Notice: Use of undefined constant app_path - assumed 'app_path' in /Users/johannes/Dropbox/Code/htdocs/sub2home/dev/server/app/controllers/api/services/DecodeQRCodeController.php line 31' in /Users/johannes/Dropbox/Code/htdocs/sub2home/dev/server/app/controllers/api/services/DecodeQRCodeController.php:31
Stack trace:
#0 /Users/johannes/Dropbox/Code/htdocs/sub2home/dev/server/app/controllers/api/services/DecodeQRCodeController.php(31): Symfony\Component\HttpKernel\Debug\ErrorHandler->handle(8, 'Use of undefine...', '/Users/johannes...', 31, Array)
#1 [internal function]: App\Controllers\Api\Services\DecodeQRCodeController->decode()
#2 /Users/johannes/Dropbox/Code/htdocs/sub2home/dev/server/vendor/laravel/framework/src/Illuminate/Routing/Controllers/Controller.php(138): call_user_func_array(Array, Array)
#3 /Users/johannes/Dropbox/Code/htdocs/sub2home/dev/server/vendor/laravel/framework/src/Illuminate/Routing/Controllers/Controller.php(115): Illuminate\Routing\Controllers\Controller->callMethod('decode', Array)
#4 /Users/johannes/Dropbox/Code/htdocs/sub2home/dev/server/bootstrap/compiled.php(6977): Illuminate\Routing\Controllers\Controller->callAction(Object(Illuminate\Foundation\Application), Object(Illuminate\Routing\Router), 'decode', Array)
#5 [internal function]: Illuminate\Routing\Router->Illuminate\Routing\{closure}()
#6 /Users/johannes/Dropbox/Code/htdocs/sub2home/dev/server/bootstrap/compiled.php(12961): call_user_func_array(Object(Closure), Array)
#7 /Users/johannes/Dropbox/Code/htdocs/sub2home/dev/server/bootstrap/compiled.php(12942): Illuminate\Routing\Route->callCallable()
#8 /Users/johannes/Dropbox/Code/htdocs/sub2home/dev/server/bootstrap/compiled.php(6997): Illuminate\Routing\Route->run(Object(Illuminate\Http\Request))
#9 /Users/johannes/Dropbox/Code/htdocs/sub2home/dev/server/bootstrap/compiled.php(946): Illuminate\Routing\Router->dispatch(Object(Illuminate\Http\Request))
#10 /Users/johannes/Dropbox/Code/htdocs/sub2home/dev/server/bootstrap/compiled.php(934): Illuminate\Foundation\Application->dispatch(Object(Illuminate\Http\Request))
#11 /Users/johannes/Dropbox/Code/htdocs/sub2home/dev/server/public/index.php(51): Illuminate\Foundation\Application->run()
#12 {main} [] []
[2013-03-21 18:14:36] log.ERROR: exception 'App\Exceptions\ServiceException' in /Users/johannes/Dropbox/Code/htdocs/sub2home/dev/server/app/controllers/services/image/DecodeQRCodeService.php:31
Stack trace:
#0 /Users/johannes/Dropbox/Code/htdocs/sub2home/dev/server/app/controllers/services/image/DecodeQRCodeService.php(16): App\Controllers\Services\Image\DecodeQRCodeService::decodeImageWithZxing('/Users/johannes...')
#1 /Users/johannes/Dropbox/Code/htdocs/sub2home/dev/server/app/controllers/api/services/DecodeQRCodeController.php(45): App\Controllers\Services\Image\DecodeQRCodeService::decodeImage('/Users/johannes...')
#2 [internal function]: App\Controllers\Api\Services\DecodeQRCodeController->decode()
#3 /Users/johannes/Dropbox/Code/htdocs/sub2home/dev/server/vendor/laravel/framework/src/Illuminate/Routing/Controllers/Controller.php(138): call_user_func_array(Array, Array)
#4 /Users/johannes/Dropbox/Code/htdocs/sub2home/dev/server/vendor/laravel/framework/src/Illuminate/Routing/Controllers/Controller.php(115): Illuminate\Routing\Controllers\Controller->callMethod('decode', Array)
#5 /Users/johannes/Dropbox/Code/htdocs/sub2home/dev/server/bootstrap/compiled.php(6977): Illuminate\Routing\Controllers\Controller->callAction(Object(Illuminate\Foundation\Application), Object(Illuminate\Routing\Router), 'decode', Array)
#6 [internal function]: Illuminate\Routing\Router->Illuminate\Routing\{closure}()
#7 /Users/johannes/Dropbox/Code/htdocs/sub2home/dev/server/bootstrap/compiled.php(12961): call_user_func_array(Object(Closure), Array)
#8 /Users/johannes/Dropbox/Code/htdocs/sub2home/dev/server/bootstrap/compiled.php(12942): Illuminate\Routing\Route->callCallable()
#9 /Users/johannes/Dropbox/Code/htdocs/sub2home/dev/server/bootstrap/compiled.php(6997): Illuminate\Routing\Route->run(Object(Illuminate\Http\Request))
#10 /Users/johannes/Dropbox/Code/htdocs/sub2home/dev/server/bootstrap/compiled.php(946): Illuminate\Routing\Router->dispatch(Object(Illuminate\Http\Request))
#11 /Users/johannes/Dropbox/Code/htdocs/sub2home/dev/server/bootstrap/compiled.php(934): Illuminate\Foundation\Application->dispatch(Object(Illuminate\Http\Request))
#12 /Users/johannes/Dropbox/Code/htdocs/sub2home/dev/server/public/index.php(51): Illuminate\Foundation\Application->run()
#13 {main} [] []
[2013-03-21 18:15:10] log.ERROR: exception 'App\Exceptions\ServiceException' in /Users/johannes/Dropbox/Code/htdocs/sub2home/dev/server/app/controllers/services/image/DecodeQRCodeService.php:31
Stack trace:
#0 /Users/johannes/Dropbox/Code/htdocs/sub2home/dev/server/app/controllers/services/image/DecodeQRCodeService.php(16): App\Controllers\Services\Image\DecodeQRCodeService::decodeImageWithZxing('/Users/johannes...')
#1 /Users/johannes/Dropbox/Code/htdocs/sub2home/dev/server/app/controllers/api/services/DecodeQRCodeController.php(45): App\Controllers\Services\Image\DecodeQRCodeService::decodeImage('/Users/johannes...')
#2 [internal function]: App\Controllers\Api\Services\DecodeQRCodeController->decode()
#3 /Users/johannes/Dropbox/Code/htdocs/sub2home/dev/server/vendor/laravel/framework/src/Illuminate/Routing/Controllers/Controller.php(138): call_user_func_array(Array, Array)
#4 /Users/johannes/Dropbox/Code/htdocs/sub2home/dev/server/vendor/laravel/framework/src/Illuminate/Routing/Controllers/Controller.php(115): Illuminate\Routing\Controllers\Controller->callMethod('decode', Array)
#5 /Users/johannes/Dropbox/Code/htdocs/sub2home/dev/server/bootstrap/compiled.php(6977): Illuminate\Routing\Controllers\Controller->callAction(Object(Illuminate\Foundation\Application), Object(Illuminate\Routing\Router), 'decode', Array)
#6 [internal function]: Illuminate\Routing\Router->Illuminate\Routing\{closure}()
#7 /Users/johannes/Dropbox/Code/htdocs/sub2home/dev/server/bootstrap/compiled.php(12961): call_user_func_array(Object(Closure), Array)
#8 /Users/johannes/Dropbox/Code/htdocs/sub2home/dev/server/bootstrap/compiled.php(12942): Illuminate\Routing\Route->callCallable()
#9 /Users/johannes/Dropbox/Code/htdocs/sub2home/dev/server/bootstrap/compiled.php(6997): Illuminate\Routing\Route->run(Object(Illuminate\Http\Request))
#10 /Users/johannes/Dropbox/Code/htdocs/sub2home/dev/server/bootstrap/compiled.php(946): Illuminate\Routing\Router->dispatch(Object(Illuminate\Http\Request))
#11 /Users/johannes/Dropbox/Code/htdocs/sub2home/dev/server/bootstrap/compiled.php(934): Illuminate\Foundation\Application->dispatch(Object(Illuminate\Http\Request))
#12 /Users/johannes/Dropbox/Code/htdocs/sub2home/dev/server/public/index.php(51): Illuminate\Foundation\Application->run()
#13 {main} [] []
[2013-03-21 18:15:55] log.ERROR: exception 'App\Exceptions\ServiceException' in /Users/johannes/Dropbox/Code/htdocs/sub2home/dev/server/app/controllers/services/image/DecodeQRCodeService.php:31
Stack trace:
#0 /Users/johannes/Dropbox/Code/htdocs/sub2home/dev/server/app/controllers/services/image/DecodeQRCodeService.php(16): App\Controllers\Services\Image\DecodeQRCodeService::decodeImageWithZxing('/Users/johannes...')
#1 /Users/johannes/Dropbox/Code/htdocs/sub2home/dev/server/app/controllers/api/services/DecodeQRCodeController.php(45): App\Controllers\Services\Image\DecodeQRCodeService::decodeImage('/Users/johannes...')
#2 [internal function]: App\Controllers\Api\Services\DecodeQRCodeController->decode()
#3 /Users/johannes/Dropbox/Code/htdocs/sub2home/dev/server/vendor/laravel/framework/src/Illuminate/Routing/Controllers/Controller.php(138): call_user_func_array(Array, Array)
#4 /Users/johannes/Dropbox/Code/htdocs/sub2home/dev/server/vendor/laravel/framework/src/Illuminate/Routing/Controllers/Controller.php(115): Illuminate\Routing\Controllers\Controller->callMethod('decode', Array)
#5 /Users/johannes/Dropbox/Code/htdocs/sub2home/dev/server/bootstrap/compiled.php(6977): Illuminate\Routing\Controllers\Controller->callAction(Object(Illuminate\Foundation\Application), Object(Illuminate\Routing\Router), 'decode', Array)
#6 [internal function]: Illuminate\Routing\Router->Illuminate\Routing\{closure}()
#7 /Users/johannes/Dropbox/Code/htdocs/sub2home/dev/server/bootstrap/compiled.php(12961): call_user_func_array(Object(Closure), Array)
#8 /Users/johannes/Dropbox/Code/htdocs/sub2home/dev/server/bootstrap/compiled.php(12942): Illuminate\Routing\Route->callCallable()
#9 /Users/johannes/Dropbox/Code/htdocs/sub2home/dev/server/bootstrap/compiled.php(6997): Illuminate\Routing\Route->run(Object(Illuminate\Http\Request))
#10 /Users/johannes/Dropbox/Code/htdocs/sub2home/dev/server/bootstrap/compiled.php(946): Illuminate\Routing\Router->dispatch(Object(Illuminate\Http\Request))
#11 /Users/johannes/Dropbox/Code/htdocs/sub2home/dev/server/bootstrap/compiled.php(934): Illuminate\Foundation\Application->dispatch(Object(Illuminate\Http\Request))
#12 /Users/johannes/Dropbox/Code/htdocs/sub2home/dev/server/public/index.php(51): Illuminate\Foundation\Application->run()
#13 {main} [] []
[2013-03-21 19:50:10] log.ERROR: exception 'App\Exceptions\ServiceException' in /Users/johannes/Dropbox/Code/htdocs/sub2home/dev/server/app/controllers/services/image/DecodeQRCodeService.php:31
Stack trace:
#0 /Users/johannes/Dropbox/Code/htdocs/sub2home/dev/server/app/controllers/services/image/DecodeQRCodeService.php(16): App\Controllers\Services\Image\DecodeQRCodeService::decodeImageWithZxing('/Users/johannes...')
#1 /Users/johannes/Dropbox/Code/htdocs/sub2home/dev/server/app/controllers/api/services/DecodeQRCodeController.php(45): App\Controllers\Services\Image\DecodeQRCodeService::decodeImage('/Users/johannes...')
#2 [internal function]: App\Controllers\Api\Services\DecodeQRCodeController->decode()
#3 /Users/johannes/Dropbox/Code/htdocs/sub2home/dev/server/vendor/laravel/framework/src/Illuminate/Routing/Controllers/Controller.php(138): call_user_func_array(Array, Array)
#4 /Users/johannes/Dropbox/Code/htdocs/sub2home/dev/server/vendor/laravel/framework/src/Illuminate/Routing/Controllers/Controller.php(115): Illuminate\Routing\Controllers\Controller->callMethod('decode', Array)
#5 /Users/johannes/Dropbox/Code/htdocs/sub2home/dev/server/bootstrap/compiled.php(6977): Illuminate\Routing\Controllers\Controller->callAction(Object(Illuminate\Foundation\Application), Object(Illuminate\Routing\Router), 'decode', Array)
#6 [internal function]: Illuminate\Routing\Router->Illuminate\Routing\{closure}()
#7 /Users/johannes/Dropbox/Code/htdocs/sub2home/dev/server/bootstrap/compiled.php(12961): call_user_func_array(Object(Closure), Array)
#8 /Users/johannes/Dropbox/Code/htdocs/sub2home/dev/server/bootstrap/compiled.php(12942): Illuminate\Routing\Route->callCallable()
#9 /Users/johannes/Dropbox/Code/htdocs/sub2home/dev/server/bootstrap/compiled.php(6997): Illuminate\Routing\Route->run(Object(Illuminate\Http\Request))
#10 /Users/johannes/Dropbox/Code/htdocs/sub2home/dev/server/bootstrap/compiled.php(946): Illuminate\Routing\Router->dispatch(Object(Illuminate\Http\Request))
#11 /Users/johannes/Dropbox/Code/htdocs/sub2home/dev/server/bootstrap/compiled.php(934): Illuminate\Foundation\Application->dispatch(Object(Illuminate\Http\Request))
#12 /Users/johannes/Dropbox/Code/htdocs/sub2home/dev/server/public/index.php(51): Illuminate\Foundation\Application->run()
#13 {main} [] []
[2013-03-21 19:51:00] log.ERROR: exception 'Symfony\Component\HttpKernel\Exception\FatalErrorException' with message 'Parse: syntax error, unexpected '$data' (T_VARIABLE) in /Users/johannes/Dropbox/Code/htdocs/sub2home/dev/server/app/controllers/api/services/DecodeQRCodeController.php line 41' in /Users/johannes/Dropbox/Code/htdocs/sub2home/dev/server/app/controllers/api/services/DecodeQRCodeController.php:41
Stack trace:
#0 /Users/johannes/Dropbox/Code/htdocs/sub2home/dev/server/bootstrap/compiled.php(4019): Symfony\Component\HttpKernel\Debug\ErrorHandler->handleFatal()
#1 [internal function]: Illuminate\Exception\ExceptionServiceProvider->Illuminate\Exception\{closure}()
#2 {main} [] []
[2013-03-21 20:08:16] log.ERROR: exception 'App\Exceptions\ServiceException' in /Users/johannes/Dropbox/Code/htdocs/sub2home/dev/server/app/controllers/services/image/DecodeQRCodeService.php:31
Stack trace:
#0 /Users/johannes/Dropbox/Code/htdocs/sub2home/dev/server/app/controllers/services/image/DecodeQRCodeService.php(16): App\Controllers\Services\Image\DecodeQRCodeService::decodeImageWithZxing('/Users/johannes...')
#1 /Users/johannes/Dropbox/Code/htdocs/sub2home/dev/server/app/controllers/api/services/DecodeQRCodeController.php(47): App\Controllers\Services\Image\DecodeQRCodeService::decodeImage('/Users/johannes...')
#2 [internal function]: App\Controllers\Api\Services\DecodeQRCodeController->decode()
#3 /Users/johannes/Dropbox/Code/htdocs/sub2home/dev/server/vendor/laravel/framework/src/Illuminate/Routing/Controllers/Controller.php(138): call_user_func_array(Array, Array)
#4 /Users/johannes/Dropbox/Code/htdocs/sub2home/dev/server/vendor/laravel/framework/src/Illuminate/Routing/Controllers/Controller.php(115): Illuminate\Routing\Controllers\Controller->callMethod('decode', Array)
#5 /Users/johannes/Dropbox/Code/htdocs/sub2home/dev/server/bootstrap/compiled.php(6977): Illuminate\Routing\Controllers\Controller->callAction(Object(Illuminate\Foundation\Application), Object(Illuminate\Routing\Router), 'decode', Array)
#6 [internal function]: Illuminate\Routing\Router->Illuminate\Routing\{closure}()
#7 /Users/johannes/Dropbox/Code/htdocs/sub2home/dev/server/bootstrap/compiled.php(12961): call_user_func_array(Object(Closure), Array)
#8 /Users/johannes/Dropbox/Code/htdocs/sub2home/dev/server/bootstrap/compiled.php(12942): Illuminate\Routing\Route->callCallable()
#9 /Users/johannes/Dropbox/Code/htdocs/sub2home/dev/server/bootstrap/compiled.php(6997): Illuminate\Routing\Route->run(Object(Illuminate\Http\Request))
#10 /Users/johannes/Dropbox/Code/htdocs/sub2home/dev/server/bootstrap/compiled.php(946): Illuminate\Routing\Router->dispatch(Object(Illuminate\Http\Request))
#11 /Users/johannes/Dropbox/Code/htdocs/sub2home/dev/server/bootstrap/compiled.php(934): Illuminate\Foundation\Application->dispatch(Object(Illuminate\Http\Request))
#12 /Users/johannes/Dropbox/Code/htdocs/sub2home/dev/server/public/index.php(51): Illuminate\Foundation\Application->run()
#13 {main} [] []
[2013-03-21 20:20:55] log.ERROR: exception 'ErrorException' with message 'Notice: Undefined variable: imgstr in /Users/johannes/Dropbox/Code/htdocs/sub2home/dev/server/app/controllers/api/services/DecodeQRCodeController.php line 35' in /Users/johannes/Dropbox/Code/htdocs/sub2home/dev/server/app/controllers/api/services/DecodeQRCodeController.php:35
Stack trace:
#0 /Users/johannes/Dropbox/Code/htdocs/sub2home/dev/server/app/controllers/api/services/DecodeQRCodeController.php(35): Symfony\Component\HttpKernel\Debug\ErrorHandler->handle(8, 'Undefined varia...', '/Users/johannes...', 35, Array)
#1 [internal function]: App\Controllers\Api\Services\DecodeQRCodeController->decode()
#2 /Users/johannes/Dropbox/Code/htdocs/sub2home/dev/server/vendor/laravel/framework/src/Illuminate/Routing/Controllers/Controller.php(138): call_user_func_array(Array, Array)
#3 /Users/johannes/Dropbox/Code/htdocs/sub2home/dev/server/vendor/laravel/framework/src/Illuminate/Routing/Controllers/Controller.php(115): Illuminate\Routing\Controllers\Controller->callMethod('decode', Array)
#4 /Users/johannes/Dropbox/Code/htdocs/sub2home/dev/server/bootstrap/compiled.php(6977): Illuminate\Routing\Controllers\Controller->callAction(Object(Illuminate\Foundation\Application), Object(Illuminate\Routing\Router), 'decode', Array)
#5 [internal function]: Illuminate\Routing\Router->Illuminate\Routing\{closure}()
#6 /Users/johannes/Dropbox/Code/htdocs/sub2home/dev/server/bootstrap/compiled.php(12961): call_user_func_array(Object(Closure), Array)
#7 /Users/johannes/Dropbox/Code/htdocs/sub2home/dev/server/bootstrap/compiled.php(12942): Illuminate\Routing\Route->callCallable()
#8 /Users/johannes/Dropbox/Code/htdocs/sub2home/dev/server/bootstrap/compiled.php(6997): Illuminate\Routing\Route->run(Object(Illuminate\Http\Request))
#9 /Users/johannes/Dropbox/Code/htdocs/sub2home/dev/server/bootstrap/compiled.php(946): Illuminate\Routing\Router->dispatch(Object(Illuminate\Http\Request))
#10 /Users/johannes/Dropbox/Code/htdocs/sub2home/dev/server/bootstrap/compiled.php(934): Illuminate\Foundation\Application->dispatch(Object(Illuminate\Http\Request))
#11 /Users/johannes/Dropbox/Code/htdocs/sub2home/dev/server/public/index.php(51): Illuminate\Foundation\Application->run()
#12 {main} [] []
[2013-03-21 20:24:52] log.ERROR: exception 'ErrorException' with message 'Warning: preg_match(): No ending delimiter '^' found in /Users/johannes/Dropbox/Code/htdocs/sub2home/dev/server/app/controllers/api/services/DecodeQRCodeController.php line 35' in /Users/johannes/Dropbox/Code/htdocs/sub2home/dev/server/app/controllers/api/services/DecodeQRCodeController.php:35
Stack trace:
#0 [internal function]: Symfony\Component\HttpKernel\Debug\ErrorHandler->handle(2, 'preg_match(): N...', '/Users/johannes...', 35, Array)
#1 /Users/johannes/Dropbox/Code/htdocs/sub2home/dev/server/app/controllers/api/services/DecodeQRCodeController.php(35): preg_match('^data:image\/(p...', '/9j/4AAQSkZJRgA...')
#2 [internal function]: App\Controllers\Api\Services\DecodeQRCodeController->decode()
#3 /Users/johannes/Dropbox/Code/htdocs/sub2home/dev/server/vendor/laravel/framework/src/Illuminate/Routing/Controllers/Controller.php(138): call_user_func_array(Array, Array)
#4 /Users/johannes/Dropbox/Code/htdocs/sub2home/dev/server/vendor/laravel/framework/src/Illuminate/Routing/Controllers/Controller.php(115): Illuminate\Routing\Controllers\Controller->callMethod('decode', Array)
#5 /Users/johannes/Dropbox/Code/htdocs/sub2home/dev/server/bootstrap/compiled.php(6977): Illuminate\Routing\Controllers\Controller->callAction(Object(Illuminate\Foundation\Application), Object(Illuminate\Routing\Router), 'decode', Array)
#6 [internal function]: Illuminate\Routing\Router->Illuminate\Routing\{closure}()
#7 /Users/johannes/Dropbox/Code/htdocs/sub2home/dev/server/bootstrap/compiled.php(12961): call_user_func_array(Object(Closure), Array)
#8 /Users/johannes/Dropbox/Code/htdocs/sub2home/dev/server/bootstrap/compiled.php(12942): Illuminate\Routing\Route->callCallable()
#9 /Users/johannes/Dropbox/Code/htdocs/sub2home/dev/server/bootstrap/compiled.php(6997): Illuminate\Routing\Route->run(Object(Illuminate\Http\Request))
#10 /Users/johannes/Dropbox/Code/htdocs/sub2home/dev/server/bootstrap/compiled.php(946): Illuminate\Routing\Router->dispatch(Object(Illuminate\Http\Request))
#11 /Users/johannes/Dropbox/Code/htdocs/sub2home/dev/server/bootstrap/compiled.php(934): Illuminate\Foundation\Application->dispatch(Object(Illuminate\Http\Request))
#12 /Users/johannes/Dropbox/Code/htdocs/sub2home/dev/server/public/index.php(51): Illuminate\Foundation\Application->run()
#13 {main} [] []
[2013-03-21 20:26:58] log.ERROR: exception 'ErrorException' with message 'Warning: preg_match(): Unknown modifier '(' in /Users/johannes/Dropbox/Code/htdocs/sub2home/dev/server/app/controllers/api/services/DecodeQRCodeController.php line 35' in /Users/johannes/Dropbox/Code/htdocs/sub2home/dev/server/app/controllers/api/services/DecodeQRCodeController.php:35
Stack trace:
#0 [internal function]: Symfony\Component\HttpKernel\Debug\ErrorHandler->handle(2, 'preg_match(): U...', '/Users/johannes...', 35, Array)
#1 /Users/johannes/Dropbox/Code/htdocs/sub2home/dev/server/app/controllers/api/services/DecodeQRCodeController.php(35): preg_match('/^data:image/(p...', '/9j/4AAQSkZJRgA...')
#2 [internal function]: App\Controllers\Api\Services\DecodeQRCodeController->decode()
#3 /Users/johannes/Dropbox/Code/htdocs/sub2home/dev/server/vendor/laravel/framework/src/Illuminate/Routing/Controllers/Controller.php(138): call_user_func_array(Array, Array)
#4 /Users/johannes/Dropbox/Code/htdocs/sub2home/dev/server/vendor/laravel/framework/src/Illuminate/Routing/Controllers/Controller.php(115): Illuminate\Routing\Controllers\Controller->callMethod('decode', Array)
#5 /Users/johannes/Dropbox/Code/htdocs/sub2home/dev/server/bootstrap/compiled.php(6977): Illuminate\Routing\Controllers\Controller->callAction(Object(Illuminate\Foundation\Application), Object(Illuminate\Routing\Router), 'decode', Array)
#6 [internal function]: Illuminate\Routing\Router->Illuminate\Routing\{closure}()
#7 /Users/johannes/Dropbox/Code/htdocs/sub2home/dev/server/bootstrap/compiled.php(12961): call_user_func_array(Object(Closure), Array)
#8 /Users/johannes/Dropbox/Code/htdocs/sub2home/dev/server/bootstrap/compiled.php(12942): Illuminate\Routing\Route->callCallable()
#9 /Users/johannes/Dropbox/Code/htdocs/sub2home/dev/server/bootstrap/compiled.php(6997): Illuminate\Routing\Route->run(Object(Illuminate\Http\Request))
#10 /Users/johannes/Dropbox/Code/htdocs/sub2home/dev/server/bootstrap/compiled.php(946): Illuminate\Routing\Router->dispatch(Object(Illuminate\Http\Request))
#11 /Users/johannes/Dropbox/Code/htdocs/sub2home/dev/server/bootstrap/compiled.php(934): Illuminate\Foundation\Application->dispatch(Object(Illuminate\Http\Request))
#12 /Users/johannes/Dropbox/Code/htdocs/sub2home/dev/server/public/index.php(51): Illuminate\Foundation\Application->run()
#13 {main} [] []
[2013-03-21 20:35:46] log.ERROR: exception 'Symfony\Component\HttpKernel\Exception\FatalErrorException' with message 'Parse: syntax error, unexpected '/' in /Users/johannes/Dropbox/Code/htdocs/sub2home/dev/server/app/controllers/api/services/DecodeQRCodeController.php line 33' in /Users/johannes/Dropbox/Code/htdocs/sub2home/dev/server/app/controllers/api/services/DecodeQRCodeController.php:33
Stack trace:
#0 /Users/johannes/Dropbox/Code/htdocs/sub2home/dev/server/bootstrap/compiled.php(4019): Symfony\Component\HttpKernel\Debug\ErrorHandler->handleFatal()
#1 [internal function]: Illuminate\Exception\ExceptionServiceProvider->Illuminate\Exception\{closure}()
#2 {main} [] []
[2013-03-21 20:40:40] log.ERROR: exception 'ErrorException' with message 'Warning: preg_match(): Delimiter must not be alphanumeric or backslash in /Users/johannes/Dropbox/Code/htdocs/sub2home/dev/server/app/controllers/api/services/DecodeQRCodeController.php line 35' in /Users/johannes/Dropbox/Code/htdocs/sub2home/dev/server/app/controllers/api/services/DecodeQRCodeController.php:35
Stack trace:
#0 [internal function]: Symfony\Component\HttpKernel\Debug\ErrorHandler->handle(2, 'preg_match(): D...', '/Users/johannes...', 35, Array)
#1 /Users/johannes/Dropbox/Code/htdocs/sub2home/dev/server/app/controllers/api/services/DecodeQRCodeController.php(35): preg_match('data', '/9j/4AAQSkZJRgA...')
#2 [internal function]: App\Controllers\Api\Services\DecodeQRCodeController->decode()
#3 /Users/johannes/Dropbox/Code/htdocs/sub2home/dev/server/vendor/laravel/framework/src/Illuminate/Routing/Controllers/Controller.php(138): call_user_func_array(Array, Array)
#4 /Users/johannes/Dropbox/Code/htdocs/sub2home/dev/server/vendor/laravel/framework/src/Illuminate/Routing/Controllers/Controller.php(115): Illuminate\Routing\Controllers\Controller->callMethod('decode', Array)
#5 /Users/johannes/Dropbox/Code/htdocs/sub2home/dev/server/bootstrap/compiled.php(6977): Illuminate\Routing\Controllers\Controller->callAction(Object(Illuminate\Foundation\Application), Object(Illuminate\Routing\Router), 'decode', Array)
#6 [internal function]: Illuminate\Routing\Router->Illuminate\Routing\{closure}()
#7 /Users/johannes/Dropbox/Code/htdocs/sub2home/dev/server/bootstrap/compiled.php(12961): call_user_func_array(Object(Closure), Array)
#8 /Users/johannes/Dropbox/Code/htdocs/sub2home/dev/server/bootstrap/compiled.php(12942): Illuminate\Routing\Route->callCallable()
#9 /Users/johannes/Dropbox/Code/htdocs/sub2home/dev/server/bootstrap/compiled.php(6997): Illuminate\Routing\Route->run(Object(Illuminate\Http\Request))
#10 /Users/johannes/Dropbox/Code/htdocs/sub2home/dev/server/bootstrap/compiled.php(946): Illuminate\Routing\Router->dispatch(Object(Illuminate\Http\Request))
#11 /Users/johannes/Dropbox/Code/htdocs/sub2home/dev/server/bootstrap/compiled.php(934): Illuminate\Foundation\Application->dispatch(Object(Illuminate\Http\Request))
#12 /Users/johannes/Dropbox/Code/htdocs/sub2home/dev/server/public/index.php(51): Illuminate\Foundation\Application->run()
#13 {main} [] []
[2013-03-21 21:36:12] log.ERROR: exception 'ErrorException' with message 'Catchable Fatal Error: Argument 1 passed to Illuminate\Validation\Factory::make() must be of the type array, boolean given, called in /Users/johannes/Dropbox/Code/htdocs/sub2home/dev/server/bootstrap/compiled.php on line 4262 and defined in /Users/johannes/Dropbox/Code/htdocs/sub2home/dev/server/vendor/laravel/framework/src/Illuminate/Validation/Factory.php line 62' in /Users/johannes/Dropbox/Code/htdocs/sub2home/dev/server/vendor/laravel/framework/src/Illuminate/Validation/Factory.php:62
Stack trace:
#0 /Users/johannes/Dropbox/Code/htdocs/sub2home/dev/server/vendor/laravel/framework/src/Illuminate/Validation/Factory.php(62): Symfony\Component\HttpKernel\Debug\ErrorHandler->handle(4096, 'Argument 1 pass...', '/Users/johannes...', 62, Array)
#1 /Users/johannes/Dropbox/Code/htdocs/sub2home/dev/server/bootstrap/compiled.php(4262): Illuminate\Validation\Factory->make(false, Array)
#2 /Users/johannes/Dropbox/Code/htdocs/sub2home/dev/server/app/controllers/api/services/DecodeQRCodeController.php(24): Illuminate\Support\Facades\Facade::__callStatic('make', Array)
#3 /Users/johannes/Dropbox/Code/htdocs/sub2home/dev/server/app/controllers/api/services/DecodeQRCodeController.php(24): Illuminate\Support\Facades\Validator::make(false, Array)
#4 [internal function]: App\Controllers\Api\Services\DecodeQRCodeController->decode()
#5 /Users/johannes/Dropbox/Code/htdocs/sub2home/dev/server/vendor/laravel/framework/src/Illuminate/Routing/Controllers/Controller.php(138): call_user_func_array(Array, Array)
#6 /Users/johannes/Dropbox/Code/htdocs/sub2home/dev/server/vendor/laravel/framework/src/Illuminate/Routing/Controllers/Controller.php(115): Illuminate\Routing\Controllers\Controller->callMethod('decode', Array)
#7 /Users/johannes/Dropbox/Code/htdocs/sub2home/dev/server/bootstrap/compiled.php(6977): Illuminate\Routing\Controllers\Controller->callAction(Object(Illuminate\Foundation\Application), Object(Illuminate\Routing\Router), 'decode', Array)
#8 [internal function]: Illuminate\Routing\Router->Illuminate\Routing\{closure}()
#9 /Users/johannes/Dropbox/Code/htdocs/sub2home/dev/server/bootstrap/compiled.php(12961): call_user_func_array(Object(Closure), Array)
#10 /Users/johannes/Dropbox/Code/htdocs/sub2home/dev/server/bootstrap/compiled.php(12942): Illuminate\Routing\Route->callCallable()
#11 /Users/johannes/Dropbox/Code/htdocs/sub2home/dev/server/bootstrap/compiled.php(6997): Illuminate\Routing\Route->run(Object(Illuminate\Http\Request))
#12 /Users/johannes/Dropbox/Code/htdocs/sub2home/dev/server/bootstrap/compiled.php(946): Illuminate\Routing\Router->dispatch(Object(Illuminate\Http\Request))
#13 /Users/johannes/Dropbox/Code/htdocs/sub2home/dev/server/bootstrap/compiled.php(934): Illuminate\Foundation\Application->dispatch(Object(Illuminate\Http\Request))
#14 /Users/johannes/Dropbox/Code/htdocs/sub2home/dev/server/public/index.php(51): Illuminate\Foundation\Application->run()
#15 {main} [] []
[2013-03-21 21:54:48] log.ERROR: exception 'App\Exceptions\ServiceException' in /Users/johannes/Dropbox/Code/htdocs/sub2home/dev/server/app/controllers/services/image/DecodeQRCodeService.php:31
Stack trace:
#0 /Users/johannes/Dropbox/Code/htdocs/sub2home/dev/server/app/controllers/services/image/DecodeQRCodeService.php(16): App\Controllers\Services\Image\DecodeQRCodeService::decodeImageWithZxing('/Users/johannes...')
#1 /Users/johannes/Dropbox/Code/htdocs/sub2home/dev/server/app/controllers/api/services/DecodeQRCodeController.php(52): App\Controllers\Services\Image\DecodeQRCodeService::decodeImage('/Users/johannes...')
#2 [internal function]: App\Controllers\Api\Services\DecodeQRCodeController->decode()
#3 /Users/johannes/Dropbox/Code/htdocs/sub2home/dev/server/vendor/laravel/framework/src/Illuminate/Routing/Controllers/Controller.php(138): call_user_func_array(Array, Array)
#4 /Users/johannes/Dropbox/Code/htdocs/sub2home/dev/server/vendor/laravel/framework/src/Illuminate/Routing/Controllers/Controller.php(115): Illuminate\Routing\Controllers\Controller->callMethod('decode', Array)
#5 /Users/johannes/Dropbox/Code/htdocs/sub2home/dev/server/bootstrap/compiled.php(6977): Illuminate\Routing\Controllers\Controller->callAction(Object(Illuminate\Foundation\Application), Object(Illuminate\Routing\Router), 'decode', Array)
#6 [internal function]: Illuminate\Routing\Router->Illuminate\Routing\{closure}()
#7 /Users/johannes/Dropbox/Code/htdocs/sub2home/dev/server/bootstrap/compiled.php(12961): call_user_func_array(Object(Closure), Array)
#8 /Users/johannes/Dropbox/Code/htdocs/sub2home/dev/server/bootstrap/compiled.php(12942): Illuminate\Routing\Route->callCallable()
#9 /Users/johannes/Dropbox/Code/htdocs/sub2home/dev/server/bootstrap/compiled.php(6997): Illuminate\Routing\Route->run(Object(Illuminate\Http\Request))
#10 /Users/johannes/Dropbox/Code/htdocs/sub2home/dev/server/bootstrap/compiled.php(946): Illuminate\Routing\Router->dispatch(Object(Illuminate\Http\Request))
#11 /Users/johannes/Dropbox/Code/htdocs/sub2home/dev/server/bootstrap/compiled.php(934): Illuminate\Foundation\Application->dispatch(Object(Illuminate\Http\Request))
#12 /Users/johannes/Dropbox/Code/htdocs/sub2home/dev/server/public/index.php(51): Illuminate\Foundation\Application->run()
#13 {main} [] []
[2013-03-21 22:33:19] log.ERROR: exception 'Symfony\Component\HttpKernel\Exception\FatalErrorException' with message 'Error: Class 'App\Controllers\Api\Frontend\Client\MenuBundles\StoreRelatedApiController' not found in /Users/johannes/Dropbox/Code/htdocs/sub2home/dev/server/app/controllers/api/frontend/client/menubundles/UpdateController.php line 7' in /Users/johannes/Dropbox/Code/htdocs/sub2home/dev/server/app/controllers/api/frontend/client/menubundles/UpdateController.php:7
Stack trace:
#0 /Users/johannes/Dropbox/Code/htdocs/sub2home/dev/server/bootstrap/compiled.php(4019): Symfony\Component\HttpKernel\Debug\ErrorHandler->handleFatal()
#1 [internal function]: Illuminate\Exception\ExceptionServiceProvider->Illuminate\Exception\{closure}()
#2 {main} [] []
[2013-03-21 22:40:28] log.ERROR: exception 'Symfony\Component\HttpKernel\Exception\FatalErrorException' with message 'Error: Class 'App\Controllers\Api\Frontend\Client\MenuBundles\Input' not found in /Users/johannes/Dropbox/Code/htdocs/sub2home/dev/server/app/controllers/api/frontend/client/menubundles/UpdateController.php line 16' in /Users/johannes/Dropbox/Code/htdocs/sub2home/dev/server/app/controllers/api/frontend/client/menubundles/UpdateController.php:16
Stack trace:
#0 /Users/johannes/Dropbox/Code/htdocs/sub2home/dev/server/bootstrap/compiled.php(4019): Symfony\Component\HttpKernel\Debug\ErrorHandler->handleFatal()
#1 [internal function]: Illuminate\Exception\ExceptionServiceProvider->Illuminate\Exception\{closure}()
#2 {main} [] []
[2013-03-21 22:55:43] log.ERROR: exception 'Symfony\Component\HttpKernel\Exception\NotFoundHttpException' in /Users/johannes/Dropbox/Code/htdocs/sub2home/dev/server/vendor/laravel/framework/src/Illuminate/Routing/Controllers/Controller.php:302
Stack trace:
#0 /Users/johannes/Dropbox/Code/htdocs/sub2home/dev/server/app/controllers/api/frontend/client/menubundles/UpdateController.php(41): Illuminate\Routing\Controllers\Controller->__call('isLastActiveMen...', Array)
#1 /Users/johannes/Dropbox/Code/htdocs/sub2home/dev/server/app/controllers/api/frontend/client/menubundles/UpdateController.php(41): App\Controllers\Api\Frontend\Client\MenuBundles\UpdateController->isLastActiveMenu()
#2 [internal function]: App\Controllers\Api\Frontend\Client\MenuBundles\UpdateController->route('memmingen', '1')
#3 /Users/johannes/Dropbox/Code/htdocs/sub2home/dev/server/vendor/laravel/framework/src/Illuminate/Routing/Controllers/Controller.php(138): call_user_func_array(Array, Array)
#4 /Users/johannes/Dropbox/Code/htdocs/sub2home/dev/server/vendor/laravel/framework/src/Illuminate/Routing/Controllers/Controller.php(115): Illuminate\Routing\Controllers\Controller->callMethod('route', Array)
#5 /Users/johannes/Dropbox/Code/htdocs/sub2home/dev/server/bootstrap/compiled.php(6977): Illuminate\Routing\Controllers\Controller->callAction(Object(Illuminate\Foundation\Application), Object(Illuminate\Routing\Router), 'route', Array)
#6 [internal function]: Illuminate\Routing\Router->Illuminate\Routing\{closure}('memmingen', '1')
#7 /Users/johannes/Dropbox/Code/htdocs/sub2home/dev/server/bootstrap/compiled.php(12961): call_user_func_array(Object(Closure), Array)
#8 /Users/johannes/Dropbox/Code/htdocs/sub2home/dev/server/bootstrap/compiled.php(12942): Illuminate\Routing\Route->callCallable()
#9 /Users/johannes/Dropbox/Code/htdocs/sub2home/dev/server/bootstrap/compiled.php(6997): Illuminate\Routing\Route->run(Object(Illuminate\Http\Request))
#10 /Users/johannes/Dropbox/Code/htdocs/sub2home/dev/server/bootstrap/compiled.php(946): Illuminate\Routing\Router->dispatch(Object(Illuminate\Http\Request))
#11 /Users/johannes/Dropbox/Code/htdocs/sub2home/dev/server/bootstrap/compiled.php(934): Illuminate\Foundation\Application->dispatch(Object(Illuminate\Http\Request))
#12 /Users/johannes/Dropbox/Code/htdocs/sub2home/dev/server/public/index.php(51): Illuminate\Foundation\Application->run()
#13 {main} [] []
[2013-03-21 22:55:48] log.ERROR: exception 'Symfony\Component\HttpKernel\Exception\NotFoundHttpException' in /Users/johannes/Dropbox/Code/htdocs/sub2home/dev/server/vendor/laravel/framework/src/Illuminate/Routing/Controllers/Controller.php:302
Stack trace:
#0 /Users/johannes/Dropbox/Code/htdocs/sub2home/dev/server/app/controllers/api/frontend/client/menubundles/UpdateController.php(41): Illuminate\Routing\Controllers\Controller->__call('isLastActiveMen...', Array)
#1 /Users/johannes/Dropbox/Code/htdocs/sub2home/dev/server/app/controllers/api/frontend/client/menubundles/UpdateController.php(41): App\Controllers\Api\Frontend\Client\MenuBundles\UpdateController->isLastActiveMenu()
#2 [internal function]: App\Controllers\Api\Frontend\Client\MenuBundles\UpdateController->route('memmingen', '1')
#3 /Users/johannes/Dropbox/Code/htdocs/sub2home/dev/server/vendor/laravel/framework/src/Illuminate/Routing/Controllers/Controller.php(138): call_user_func_array(Array, Array)
#4 /Users/johannes/Dropbox/Code/htdocs/sub2home/dev/server/vendor/laravel/framework/src/Illuminate/Routing/Controllers/Controller.php(115): Illuminate\Routing\Controllers\Controller->callMethod('route', Array)
#5 /Users/johannes/Dropbox/Code/htdocs/sub2home/dev/server/bootstrap/compiled.php(6977): Illuminate\Routing\Controllers\Controller->callAction(Object(Illuminate\Foundation\Application), Object(Illuminate\Routing\Router), 'route', Array)
#6 [internal function]: Illuminate\Routing\Router->Illuminate\Routing\{closure}('memmingen', '1')
#7 /Users/johannes/Dropbox/Code/htdocs/sub2home/dev/server/bootstrap/compiled.php(12961): call_user_func_array(Object(Closure), Array)
#8 /Users/johannes/Dropbox/Code/htdocs/sub2home/dev/server/bootstrap/compiled.php(12942): Illuminate\Routing\Route->callCallable()
#9 /Users/johannes/Dropbox/Code/htdocs/sub2home/dev/server/bootstrap/compiled.php(6997): Illuminate\Routing\Route->run(Object(Illuminate\Http\Request))
#10 /Users/johannes/Dropbox/Code/htdocs/sub2home/dev/server/bootstrap/compiled.php(946): Illuminate\Routing\Router->dispatch(Object(Illuminate\Http\Request))
#11 /Users/johannes/Dropbox/Code/htdocs/sub2home/dev/server/bootstrap/compiled.php(934): Illuminate\Foundation\Application->dispatch(Object(Illuminate\Http\Request))
#12 /Users/johannes/Dropbox/Code/htdocs/sub2home/dev/server/public/index.php(51): Illuminate\Foundation\Application->run()
#13 {main} [] []
[2013-03-21 23:40:46] log.ERROR: exception 'Symfony\Component\HttpKernel\Exception\FatalErrorException' with message 'Error: Class 'App\Controllers\Api\Frontend\Client\MenuUpgrades\StoreRelatedApiController' not found in /Users/johannes/Dropbox/Code/htdocs/sub2home/dev/server/app/controllers/api/frontend/client/menuupgrades/UpdateController.php line 7' in /Users/johannes/Dropbox/Code/htdocs/sub2home/dev/server/app/controllers/api/frontend/client/menuupgrades/UpdateController.php:7
Stack trace:
#0 /Users/johannes/Dropbox/Code/htdocs/sub2home/dev/server/bootstrap/compiled.php(4019): Symfony\Component\HttpKernel\Debug\ErrorHandler->handleFatal()
#1 [internal function]: Illuminate\Exception\ExceptionServiceProvider->Illuminate\Exception\{closure}()
#2 {main} [] []
